sudo: required
services:
    -   docker

before_install:
    - docker build -t th3v055i/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run th3v055i/react-test npm test -- --coverage

after_success:
    - docker build -t th3v055i/multi-client ./client
    - docker build -t th3v055i/multi-nginx ./nginx
    - docker build -t th3v055i/multi-server ./server
    - docker build -t th3v055i/multi-worker ./worker
# the above images have to be push to docker hub
# donot mis to login Docker hub by 'docker login'
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password stdin
    - docker push th3v055i/multi-client
    - docker push th3v055i/multi-nginx
    - docker push th3v055i/multi-server
    - docker push th3v055i/multi-worker
