# if prod version then the deploy section is added
sudo: required
services:
    -   docker

before_install:
    - docker build -t th3v055i/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run th3v055i/react-test npm test -- --coverage

after_success:
    - docker build -t th3v055i/multi-client ./client
    - docker build -t th3v055i/multi-nginx ./nginx
    - docker build -t th3v055i/multi-server ./server
    - docker build -t th3v055i/multi-worker ./worker
# donot mis to login Docker hub by 'docker login'
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# the above images have to be push to docker hub
    - docker push th3v055i/multi-client
    - docker push th3v055i/multi-nginx
    - docker push th3v055i/multi-server
    - docker push th3v055i/multi-worker
deploy:
    edge: true
    provider: elasticbeanstalk
    region: eu-central-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-central-1-085157154669
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY 