version: '3'
services:
    postgres: 
        image: 'postgres:latest'
    redis:
        image: 'redis:latest'
    # named before 'server' but not to confuse the nginx server the name is changed to 'api'
    # Router
    nginx:
        restart: always
        build: 
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports: 
            - '3050:80'
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        depends_on:
            - postgres
        volumes:
            # keep the '/app/node_modules' folder as it is no changes 
            - /app/node_modules
            # take everything from the ./server dir and map it to /app folder inside the container
            - ./server:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    client: 
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - /app/node_modules
            - ./client:/app
    # REDIS
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        volumes:
            - /app/node_modules
            - ./worker:/app
    